services:
    system:
        build:
            context: .docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.3/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - db
    db:
        image: mysql:8.0.19
        platform: linux/x86_64
        container_name: mysql_salse
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: salesDB
            MYSQL_USER: HanThamarat
            MYSQL_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - "./.docker/db:/var/lib/mysql:rw"
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-db:
        driver: local
